In [2]:
import numpy as np 
import pandas as pd

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
movies = movies.merge(credits, on='title')

AttributeError: 'tuple' object has no attribute 'merge'

In [14]:
print(type(movies))

<class 'tuple'>

In [15]:
print(type(credits))

<class 'pandas.core.frame.DataFrame'>

In [16]:
movies=pd.read_csv('tmdb_5000_movies.csv')

In [17]:
print(type(movies))

<class 'pandas.core.frame.DataFrame'>

In [18]:
movies = movies.merge(credits, on='title')

In [19]:
print(movies.shape)

(4809, 23)

In [20]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [21]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [24]:
movies.dropna(inplace=True)

In [26]:
movies.duplicated().sum()

0

In [28]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [29]:
import ast

In [30]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [31]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [34]:
movies['keywords']=movies['keywords'].apply(convert)

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [38]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [40]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [42]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [43]:
def detch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [44]:
movies['crew']=movies['crew'].apply(detch_director)

In [45]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [46]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [47]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [48]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [49]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [50]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [51]:
movies['tags']=movies['overview']+ movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [52]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [59]:
new_df=movies[['movie_id','title','tags']]

In [60]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\User\AppData\Local\Temp\ipykernel_5020\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [61]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [62]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [63]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\User\AppData\Local\Temp\ipykernel_5020\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [64]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [66]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [67]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [68]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [69]:
!pip install nltk

Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [70]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [75]:
def stem(text):
    y=[]
    for i in text.split():
       y.append(ps.stem(i))
    return " ".join(y)

In [73]:
ps.stem('dancing')

'danc'

In [79]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [81]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\User\AppData\Local\Temp\ipykernel_5020\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [82]:
from sklearn.metrics.pairwise import cosine_similarity

In [84]:
similarity = cosine_similarity(vectors)

In [85]:
similarity[0]

array([1.        , 0.08964215, 0.05976143, ..., 0.02519763, 0.02817181,
       0.        ])

In [86]:
sorted(similarity[0],reverse=True)

[1.0,
 0.26089696604360174,
 0.2581988897471611,
 0.25302403842552984,
 0.25110592822973776,
 0.24944382578492943,
 0.24397501823713333,
 0.243599382882345,
 0.23904572186687872,
 0.2344036154692477,
 0.22677868380553634,
 0.2238868314198225,
 0.22230800575069137,
 0.22190115272469205,
 0.22131333406899523,
 0.2193633988428327,
 0.2173253797873328,
 0.21653278478430668,
 0.2164218276749025,
 0.2162249910469341,
 0.2162249910469341,
 0.21602468994692864,
 0.21602468994692864,
 0.21251185925162067,
 0.2114722130550724,
 0.21147221305507238,
 0.21096325392232296,
 0.2059714602177749,
 0.20291986247835692,
 0.20283702113484398,
 0.19920476822239894,
 0.19889806323953876,
 0.1980534816610477,
 0.19518001458970666,
 0.19518001458970666,
 0.19451950503185494,
 0.1938916835823703,
 0.19320245583349133,
 0.19317811536651805,
 0.19166296949998196,
 0.1901597073139162,
 0.1893524273324603,
 0.1889822365046136,
 0.18832944617230335,
 0.18832944617230335,
 0.18708286933869706,
 0.18478728707195913,
 0.18478728707195913,
 0.1831403087002079,
 0.1825741858350554,
 0.18257418583505536,
 0.18018749253911176,
 0.17928429140015903,
 0.1765469659009499,
 0.1763834207376394,
 0.17622684421256032,
 0.17445567519772937,
 0.17251638983558856,
 0.17251638983558856,
 0.1717355162964367,
 0.17142857142857143,
 0.17142857142857143,
 0.17036708399998393,
 0.1690308509457033,
 0.1690308509457033,
 0.1690308509457033,
 0.1690308509457033,
 0.16903085094570328,
 0.16574838603294897,
 0.16574838603294897,
 0.16408253082847338,
 0.16265001215808886,
 0.16265001215808886,
 0.16239958858823,
 0.16239958858823,
 0.16035674514745463,
 0.16035674514745463,
 0.15971914124998493,
 0.15694120514358612,
 0.15694120514358612,
 0.1564921592871903,
 0.1553638665664663,
 0.15430334996209188,
 0.15289415743128765,
 0.15289415743128765,
 0.15289415743128765,
 0.15179418517972906,
 0.15179418517972906,
 0.15179418517972906,
 0.15118578920369088,
 0.15118578920369088,
 0.15026857675938213,
 0.14953343588376802,
 0.14754222271266348,
 0.14754222271266348,
 0.14754222271266348,
 0.14638501094227999,
 0.1456438162508838,
 0.1449427589131121,
 0.1449427589131121,
 0.1449427589131121,
 0.1449427589131121,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14285714285714285,
 0.14201432049934523,
 0.14098147537004826,
 0.14085904245475275,
 0.14085904245475275,
 0.1406421692815486,
 0.1406421692815486,
 0.13930903806377162,
 0.1389425035941821,
 0.1389425035941821,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847082,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13662601021279464,
 0.13662601021279464,
 0.13552618543578768,
 0.13533299049019168,
 0.13533299049019168,
 0.13533299049019168,
 0.13522468075656266,
 0.13522468075656266,
 0.13522468075656266,
 0.13522468075656266,
 0.13433209885189348,
 0.1336306209562122,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13259870882635919,
 0.13199091933711365,
 0.1309307341415954,
 0.13041013273932528,
 0.13041013273932528,
 0.13041013273932528,
 0.13041013273932528,
 0.1301200097264711,
 0.1301200097264711,
 0.12888481555661674,
 0.12777531299998796,
 0.12777531299998796,
 0.12777531299998796,
 0.12777531299998796,
 0.12741179785940637,
 0.12741179785940637,
 0.12741179785940637,
 0.12598815766974242,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.12555296411486888,
 0.1246111965698067,
 0.1246111965698067,
 0.12461119656980668,
 0.12344267996967351,
 0.12344267996967351,
 0.12344267996967351,
 0.12327841818038447,
 0.12327841818038447,
 0.12327841818038446,
 0.12298800925361816,
 0.12298800925361816,
 0.12298800925361816,
 0.12298800925361816,
 0.12198750911856666,
 0.12198750911856665,
 0.12143534814378325,
 0.12073632210407378,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.11952286093343935,
 0.1183452670827877,
 0.1183452670827877,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11769797726729994,
 0.11710800875382396,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11633501014942217,
 0.11609086505314302,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11501092655705902,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11428571428571427,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.1129384878631564,
 0.1129384878631564,
 0.1129384878631564,
 0.1129384878631564,
 0.1129384878631564,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.11194341570991125,
 0.11194341570991125,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.1109741904046188,
 0.11097419040461878,
 0.11065666703449763,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.11065666703449761,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10910894511799617,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10733469768527294,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10690449676496976,
 0.10631548679075009,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.1057361065275362,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10559273546969093,
 0.10460520656316097,
 0.10432810619146021,
 0.10432810619146021,
 0.1043281061914602,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1031078524452934,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10141851056742199,
 0.10101525445522107,
 0.10079052613579392,
 0.10079052613579392,
 0.09968895725584535,
 0.09960238411119947,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.0994490316197694,
 0.09944903161976938,
 0.09862273454430757,
 0.09862273454430757,
 0.09862273454430757,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09658905768325902,
 0.09658905768325902,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09583148474999097,
 0.09569487529386908,
 0.09561828874675149,
 0.09508728264112047,
 0.09467621366623016,
 0.09467621366623016,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09416472308615166,
 0.09390602830316849,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09376144618769908,
 0.09276773134741387,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09200874124564722,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09116846116771035,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09107651110783743,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.09009374626955588,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.08964214570007951,
 0.089554732567929,
 0.089554732567929,
 0.08877935232369503,
 0.08877935232369503,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.08827348295047496,
 0.0880237696271323,
 0.0880237696271323,
 0.0880237696271323,
 0.0880237696271323,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08728715609439694,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.086568731069961,
 0.086568731069961,
 0.086568731069961,
 0.08656873106996099,
 0.08656873106996099,
 0.08656873106996099,
 0.08586775814821836,
 0.08586775814821836,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.0857142857142857,
 0.08518354199999197,
 0.08518354199999197,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08386278693775347,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08322503785764788,
 0.08322503785764788,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.08199200616907877,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.08095109602454656,
 0.08024108542850393,
 0.08021849185198157,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.0791945516022682,
 0.07859774918918593,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359515,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07733088933397005,
 0.07655590023509526,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07476671794188403,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07476671794188401,
 0.07466533929465573,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07396705090823068,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07377111135633174,
 0.07333587976225689,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07244179326244427,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07171371656006362,
 0.07168504827326538,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.07100716024967263,
 0.0708769911938334,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.07049073768502413,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.0703210846407743,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06965451903188581,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06900655593423541,
 0.06837634587578276,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06776309271789384,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06761234037828133,
 0.06716604942594674,
 0.06716604942594674,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06629935441317959,
 0.06601782722034923,
 0.06601782722034923,
 0.06601782722034923,
 0.06601782722034923,
 0.0654653670707977,
 0.0654653670707977,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06506000486323554,
 0.06492654830247076,
 0.06492654830247076,
 0.06492654830247076,
 0.06492654830247076,
 0.06440081861116377,
 0.06440081861116377,
 0.06440081861116377,
 0.06440081861116377,
 0.06417479348158525,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06388765649999398,
 0.06338656910463875,
 0.06338656910463875,
 0.0628970902033151,
 0.0628970902033151,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06277648205743444,
 0.06241877839323591,
 0.06241877839323591,
 0.06224220440894771,

In [89]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(539, 0.26089696604360174),
 (1192, 0.2581988897471611),
 (507, 0.25302403842552984),
 (260, 0.25110592822973776),
 (1214, 0.24944382578492943)]

In [102]:
def recommend(movie):
   movie_index = new_df[new_df['title'] == movie].index[0]
   distances= similarity[movie_index]
   movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
   for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [104]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman

In [105]:
import pickle

In [106]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [108]:
pickle.dump(similarity,open('similarity.pkl','wb'))